stages:
  - test
  - build

vulnerabilidade_codigo:
  stage: test
  image: python:3.11-slim
  script:
    - pip install bandit
    - bandit -r src/

construir_imagem:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t artemis-soar .
    - echo "Build concluído com sucesso!"